### ISSUE TITLE
HTML Editor not disposing the dialog

### ISSUE THREAD

**Issue by iamkunalpitale** [tneotia/html-editor-enhanced#157]
<img width="1040" alt="Screenshot 2021-11-01 at 4 01 04 PM" src="https://user-images.githubusercontent.com/26413565/139658513-d6e39013-73f8-42bf-9441-1fa8370ac474.png">
How do i click the dialog button  (HTML editor not disposing in the background)

**Comment by tneotia** [comment]
Since you are using Flutter Web, you need to use the [pointer_interceptor](https://pub.dev/packages/pointer_interceptor) package. Wrap your `AlertDialog` with `PointerInterceptor` and then you can click on the yes / no buttons. 

Just FYI, any widget that is interactable and will display on top of the editor, you need to wrap with this `PointerInterceptor`.

**Comment by tneotia** [comment]
> Hello, is this issue still resolvable by wrapping the interactable widgets inside a PointerInterceptor? I thought I solved this issue as suggested like 2 months ago, but then I had to drop the project for a while, and now that I resumed working on it, I can't seem to make it work. As suggested here and on the pointer_interceptor page, I both wrapped my Drawer and an AlertDialog (which are the only widgets that would appear above the HTML editor), but both of them won't receive inputs

As far as I know it should be working by wrapping the widget, so you may be correct that it is a Flutter bug.

**Comment by iamkunalpitale** [comment]
Yes, it has been solved with PointerInterceptor

**Comment by alexandersidum** [comment]
In my case when clicking insert link on toolbar it shows dialog on top of the html editor, how do i wrap this default dialog from the package, cant seem to find way to customize it.

**Comment by alexandersidum** [comment]
> In my case when clicking insert link on toolbar it shows dialog on top of the html editor, how do i wrap this default dialog from the package, cant seem to find way to customize it.

Nevermind , i found it on #69 
But putting pointer interceptor solution doesnt seems to work, since i still cant click the field on insert link dialog and whenever i type something it typed on html editor field instead.

**Comment by rutaba1** [comment]
Happening for me as well. I have a customised dialog for adding the link but I can't seem to access the Url text field here

<img width="1061" alt="Screenshot 2022-04-03 at 11 11 37 PM" src="https://user-images.githubusercontent.com/71274568/161442034-424cfe74-5909-4f58-8b9a-e3b378c18b87.png">
a

Here's the code for the custom dialog: 
```
Future<bool> linkDialog() async {
    final text = TextEditingController();
    final url = TextEditingController();
    final textFocus = FocusNode();
    final urlFocus = FocusNode();
    final formKey = GlobalKey<FormState>();
    await showDialog(
        context: context,
        builder: (BuildContext context) {
          return PointerInterceptor(
            child: AlertDialog(
              title: Text('Insert Link'),
              scrollable: true,
              content: Form(
                key: formKey,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('Text to display',
                        style: TextStyle(fontWeight: FontWeight.bold)),
                    SizedBox(height: 10),
                    TextField(
                      controller: text,
                      focusNode: textFocus,
                      textInputAction: TextInputAction.next,
                      decoration: InputDecoration(
                        border: OutlineInputBorder(),
                        hintText: 'Text',
                      ),
                      onSubmitted: (_) {
                        urlFocus.requestFocus();
                      },
                    ),
                    SizedBox(height: 20),
                    Text('URL', style: TextStyle(fontWeight: FontWeight.bold)),
                    SizedBox(height: 10),
                    TextFormField(
                      controller: url,
                      focusNode: urlFocus,
                      textInputAction: TextInputAction.done,
                      decoration: InputDecoration(
                        border: OutlineInputBorder(),
                        hintText: 'URL',
                      ),
                      validator: (String value) {
                        if (value == null || value.isEmpty) {
                          return 'Please enter a URL!';
                        }
                        return null;
                      },
                    ),
                  ],
                ),
              ),
              actions: [
                TextButton(
                  onPressed: () {
                    setState(() {
                      showNotesUI = true;
                    });
                    Navigator.of(context).pop();
                  },
                  child: Text('Cancel'),
                ),
                TextButton(
                  onPressed: () async {
                    if (formKey.currentState.validate()) {
                      controller.insertLink(
                        text.text.isEmpty ? url.text : text.text,
                        url.text,
                        true,
                      );
                      setState(() {
                        showNotesUI = true;
                      });
                      Navigator.of(context).pop();
                    }
                  },
                  child: Text('OK'),
                )
              ],
            ),
          );
        });
    return false;
  }
```

**Comment by tneotia** [comment]
Hi @rutaba1 , this seems to be an issue in Flutter. What Flutter version are you using?

**Comment by FlyBoyA** [comment]
Is the dialog box issue resolved ?

**Comment by keyur-lc** [comment]
still this is an issue.
